=== kefik/warlight-like-game/WinformsUI/bin/Debug/Maps/Map.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://tempuri.org/XMLSchema.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/XMLSchema.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

  <xs:element name="Region">
    <xs:complexType>
      <xs:attribute name="Name" type="xs:string" use="required"></xs:attribute>
      <xs:attribute name="Army" type="xs:unsignedInt" use="optional" default="2"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="RegionType">
    <xs:attribute name="Name" type="xs:string" use="required"></xs:attribute>
    <xs:attribute name="Army" type="xs:unsignedInt" use="optional" default="2"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="RegionWithNeighboursType">
    <xs:complexContent>
      <xs:extension base="RegionType">
        <xs:sequence>
          <xs:element name="Neighbours">
            <xs:complexType>
              <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="Region" type="RegionType"></xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="Map">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element name="SuperRegion">
          <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
              <xs:element name="Region" type="RegionWithNeighboursType">
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="Bonus" type="xs:int" use="required"></xs:attribute>
          </xs:complexType>
          <xs:key name="RegionId">
            <xs:selector xpath="./Region">
            </xs:selector>
            <xs:field xpath="@Name">
            </xs:field>
          </xs:key>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string"></xs:attribute>
      <xs:attribute name="PlayersLimit" type="xs:unsignedInt"></xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== kefik/warlight-like-game/WinformsUI/bin/Debug/Maps/World.xml
<?xml version="1.0" encoding="utf-8"?>
<Map xmlns="http://tempuri.org/XMLSchema.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://tempuri.org/XMLSchema.xsd Map.xsd">
  <SuperRegions>
    <SuperRegion Name="North America" Bonus="5">
      <Region Name="Alaska">
        <Neighbours>
          <Region Name="Kamchatka"/>
          <Region Name="Alberta"/>
          <Region Name="Northwest Territory"/>
        </Neighbours>
      </Region>
      <!--<Region Name="Alaska">
      <Neighbours>
        <Region Name="string" />
      </Neighbours>
    </Region>-->
      <Region Name="Northwest Territory">
        <Neighbours>
          <Region Name="Alaska"/>
          <Region Name="Alberta"/>
          <Region Name="Greenland"/>
          <Region Name="Ontario"/>
        </Neighbours>
      </Region>
      <Region Name="Greenland">
        <Neighbours>
          <Region Name="Iceland"/>
          <Region Name="Quebec"/>
          <Region Name="Ontario"/>
          <Region Name="Northwest Territory"/>
        </Neighbours>
      </Region>
      <Region Name="Alberta">
        <Neighbours>
          <Region Name="Alaska"/>
          <Region Name="Northwest Territory"/>
          <Region Name="Ontario"/>
          <Region Name="Western United States"/>
        </Neighbours>
      </Region>
      <Region Name="Ontario">
        <Neighbours>
          <Region Name="Alberta"/>
          <Region Name="Northwest Territory"/>
          <Region Name="Quebec"/>
          <Region Name="Eastern United States"/>
          <Region Name="Western United States"/>
          <Region Name="Greenland"/>
        </Neighbours>
      </Region>
      <Region Name="Quebec">
        <Neighbours>
          <Region Name="Greenland" />
          <Region Name="Ontario"/>
          <Region Name="Eastern United States"/>
        </Neighbours>
      </Region>
      <Region Name="Western United States">
        <Neighbours>
          <Region Name="Eastern United States" />
          <Region Name="Ontario"/>
          <Region Name="Alberta"/>
          <Region Name="Central America"/>
        </Neighbours>
      </Region>
      <Region Name="Eastern United States">
        <Neighbours>
          <Region Name="Central America" />
          <Region Name="Western United States"/>
          <Region Name="Ontario"/>
          <Region Name="Quebec"/>
        </Neighbours>
      </Region>
      <Region Name="Central America">
        <Neighbours>
          <Region Name="Western United States" />
          <Region Name="Eastern United States"/>
          <Region Name="Venezuela"/>
        </Neighbours>
      </Region>
    </SuperRegion>
    <SuperRegion Name="South America" Bonus="2">
      <Region Name="Venezuela">
        <Neighbours>
          <Region Name="Central America" />
          <Region Name="Brazil"/>
          <Region Name="Peru"/>
        </Neighbours>
      </Region>
      <Region Name="Peru">
        <Neighbours>
          <Region Name="Brazil" />
          <Region Name="Venezuela"/>
          <Region Name="Argentina"/>
        </Neighbours>
      </Region>
      <Region Name="Brazil">
        <Neighbours>
          <Region Name="Venezuela"/>
          <Region Name="Peru"/>
          <Region Name="Argentina"/>
        </Neighbours>
      </Region>
      <Region Name="Argentina">
        <Neighbours>
          <Region Name="Peru" />
          <Region Name="Brazil"/>
        </Neighbours>
      </Region>
    </SuperRegion>
    <SuperRegion Name="Europe" Bonus="5">
      <Region Name="Iceland">
        <Neighbours>
          <Region Name="Greenland" />
          <Region Name="Great Britain"/>
          <Region Name="Scandinavia"/>
        </Neighbours>
      </Region>
      <Region Name="Great Britain">
        <Neighbours>
          <Region Name="Iceland" />
          <Region Name="Scandinavia"/>
          <Region Name="Western Europe"/>
          <Region Name="Northern Europe"/>
        </Neighbours>
      </Region>
      <Region Name="Scandinavia">
        <Neighbours>
          <Region Name="Iceland" />
          <Region Name="Great Britain"/>
          <Region Name="Ukraine"/>
        </Neighbours>
      </Region>
      <Region Name="Ukraine">
        <Neighbours>
          <Region Name="Northern Europe" />
          <Region Name="Southern Europe"/>
          <Region Name="Scandinavia"/>
          <Region Name="Ural"/>
          <Region Name="Kazakhstan"/>
          <Region Name="Middle East"/>
        </Neighbours>
      </Region>
      <Region Name="Western Europe">
        <Neighbours>
          <Region Name="Great Britain" />
          <Region Name="Northern Europe"/>
          <Region Name="Southern Europe"/>
          <Region Name="North Africa"/>
        </Neighbours>
      </Region>
      <Region Name="Northern Europe">
        <Neighbours>
          <Region Name="Ukraine" />
          <Region Name="Southern Europe"/>
          <Region Name="Great Britain"/>
          <Region Name="Western Europe"/>
        </Neighbours>
      </Region>
      <Region Name="Southern Europe">
        <Neighbours>
          <Region Name="Northern Europe" />
          <Region Name="Western Europe"/>
          <Region Name="North Africa"/>
          <Region Name="Middle East"/>
          <Region Name="Ukraine"/>
        </Neighbours>
      </Region>
    </SuperRegion>
    <SuperRegion Name="Africa" Bonus="3">
      <Region Name="North Africa">
        <Neighbours>
          <Region Name="Brazil" />
          <Region Name="Congo"/>
          <Region Name="East Africa"/>
          <Region Name="Egypt"/>

          <Region Name="Western Europe"/>
          <Region Name="Southern Europe"/>

          <Region Name="Brazil"/>
        </Neighbours>
      </Region>
      <Region Name="Egypt">
        <Neighbours>
          <Region Name="North Africa" />
          <Region Name="East Africa"/>

          <Region Name="Middle East"/>

          <Region Name="Southern Europe"/>
        </Neighbours>
      </Region>
      <Region Name="East Africa">
        <Neighbours>
          <Region Name="Egypt" />
          <Region Name="Congo"/>
          <Region Name="South Africa"/>
          <Region Name="Madagascar"/>
          <Region Name="North Africa"/>

          <Region Name="Middle East"/>
        </Neighbours>
      </Region>
      <Region Name="Congo">
        <Neighbours>
          <Region Name="South Africa" />
          <Region Name="North Africa"/>
          <Region Name="East Africa"/>
        </Neighbours>
      </Region>
      <Region Name="Madagascar">
        <Neighbours>
          <Region Name="South Africa" />
          <Region Name="East Africa"/>
        </Neighbours>
      </Region>
      <Region Name="South Africa">
        <Neighbours>
          <Region Name="Congo"/>
          <Region Name="Madagascar"/>
          <Region Name="East Africa"/>
        </Neighbours>
      </Region>
    </SuperRegion>
    <SuperRegion Name="Asia" Bonus="7">
      <Region Name="Ural">
        <Neighbours>
          <Region Name="Siberia" />
          <Region Name="Ukraine"/>
          <Region Name="China"/>
          <Region Name="Kazakhstan"/>
        </Neighbours>
      </Region>
      <Region Name="Siberia">
        <Neighbours>
          <Region Name="Irkutsk" />
          <Region Name="Mongolia"/>
          <Region Name="Ural"/>
          <Region Name="Yakutsk"/>
          <Region Name="China"/>
        </Neighbours>
      </Region>
      <Region Name="Yakutsk">
        <Neighbours>
          <Region Name="Siberia" />
          <Region Name="Irkutsk"/>
          <Region Name="Kamchatka"/>
        </Neighbours>
      </Region>
      <Region Name="Kamchatka">
        <Neighbours>
          <Region Name="Irkutsk" />
          <Region Name="Mongolia"/>
          <Region Name="Japan"/>
          <Region Name="Alaska"/>
          <Region Name="Yakutsk"/>
        </Neighbours>
      </Region>
      <Region Name="Irkutsk">
        <Neighbours>
          <Region Name="Mongolia" />
          <Region Name="Siberia"/>
          <Region Name="Yakutsk"/>
          <Region Name="Kamchatka"/>
        </Neighbours>
      </Region>
      <Region Name="Kazakhstan">
        <Neighbours>
          <Region Name="Middle East" />
          <Region Name="Ural"/>
          <Region Name="Ukraine"/>
          <Region Name="India"/>
          <Region Name="China"/>
        </Neighbours>
      </Region>
      <Region Name="China">
        <Neighbours>
          <Region Name="Mongolia" />
          <Region Name="Ural"/>
          <Region Name="Siberia"/>
          <Region Name="India"/>
          <Region Name="Sian"/>
          <Region Name="Kazakhstan"/>
        </Neighbours>
      </Region>
      <Region Name="Mongolia">
        <Neighbours>
          <Region Name="Irkutsk" />
          <Region Name="Japan"/>
          <Region Name="Siberia"/>
          <Region Name="China"/>
          <Region Name="Kamchatka"/>
        </Neighbours>
      </Region>
      <Region Name="Japan">
        <Neighbours>
          <Region Name="Mongolia" />
          <Region Name="Kamchatka"/>
        </Neighbours>
      </Region>
      <Region Name="Middle East">
        <Neighbours>
          <Region Name="Southern Europe" />
          <Region Name="Ukraine"/>
          <Region Name="India"/>
          <Region Name="Egypt"/>
          <Region Name="Kazakhstan"/>
          <Region Name="East Africa"/>
        </Neighbours>
      </Region>
      <Region Name="India">
        <Neighbours>
          <Region Name="Middle East" />
          <Region Name="China"/>
          <Region Name="Sian"/>
          <Region Name="Kazakhstan"/>
        </Neighbours>
      </Region>
      <Region Name="Siam">
        <Neighbours>
          <Region Name="India" />
          <Region Name="China"/>
          <Region Name="Indonesia"/>
        </Neighbours>
      </Region>
    </SuperRegion>
    <SuperRegion Name="Australia" Bonus="2">
      <Region Name="Indonesia">
        <Neighbours>
